# Generated by Django 5.1.4 on 2025-04-29 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BidXpert_app', '0003_bid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bid',
        ),
    ]
