# Generated by Django 5.1.4 on 2025-05-01 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BidXpert_app', '0006_rename_amount_bid_bid_amount_alter_product_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='current_price',
        ),
        migrations.DeleteModel(
            name='Bid',
        ),
    ]
