# Generated by Django 5.1.4 on 2025-05-05 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BidXpert_app', '0008_bid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bid',
        ),
    ]
