# Generated by Django 5.1.4 on 2025-05-08 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BidXpert_app', '0010_contactmessage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactmessage',
            old_name='submitted_at',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
