# Generated by Django 5.1.4 on 2025-05-12 06:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BidXpert_app', '0011_rename_submitted_at_contactmessage_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auction_Listing',
            fields=[
                ('listing_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('auction_start_time', models.DateTimeField()),
                ('auction_end_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bid_time', models.DateTimeField(auto_now_add=True)),
                ('auction_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BidXpert_app.auction_listing')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
