# Generated by Django 5.1.4 on 2025-05-12 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BidXpert_app', '0012_auction_listing_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction_listing',
            name='Product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='BidXpert_app.product'),
            preserve_default=False,
        ),
    ]
