# Generated by Django 5.1.4 on 2025-05-12 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BidXpert_app', '0013_auction_listing_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction_listing',
            name='Product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BidXpert_app.product'),
        ),
    ]
