# Generated by Django 5.1.4 on 2025-05-12 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BidXpert_app', '0014_alter_auction_listing_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='auction_item',
        ),
        migrations.RemoveField(
            model_name='bid',
            name='user',
        ),
        migrations.DeleteModel(
            name='Auction_Listing',
        ),
        migrations.DeleteModel(
            name='Bid',
        ),
    ]
