# Generated by Django 5.1.4 on 2025-05-16 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BidXpert_app', '0017_product_current_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
