# Generated by Django 5.1.4 on 2025-05-26 06:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BidXpert_app', '0018_bid_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='date',
        ),
        migrations.RemoveField(
            model_name='product',
            name='time',
        ),
        migrations.AddField(
            model_name='product',
            name='end_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
