# Generated by Django 5.1.4 on 2025-05-26 07:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BidXpert_app', '0021_remove_product_date_remove_product_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='product',
            name='winner',
        ),
        migrations.AddField(
            model_name='product',
            name='date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='time',
            field=models.TimeField(blank=True, default=datetime.time, null=True),
        ),
    ]
