# Generated by Django 5.1.4 on 2025-05-28 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BidXpert_app', '0024_remove_product_end_date_remove_product_winner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
