# Generated by Django 5.1.4 on 2025-05-28 06:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BidXpert_app', '0026_product_is_sold'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_winner', to=settings.AUTH_USER_MODEL),
        ),
    ]
