# Generated by Django 5.1.4 on 2025-06-13 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BidXpert_app', '0029_customuser_is_email_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_email_verified',
        ),
    ]
